#!/bin/bash
./build/LockTester --name milan --time 5 --threads 16 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 48 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 80 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 112 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 8 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 40 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 72 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 104 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 1 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 32 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 64 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 96 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 128 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 24 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 56 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 88 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 120 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 16 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 48 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 80 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 112 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 8 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 40 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 72 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 104 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 1 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 32 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 64 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 96 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 128 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 24 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 56 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 88 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 120 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 16 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 48 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 80 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 112 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 8 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 40 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 72 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 104 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 1 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 32 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 64 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 96 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 128 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 24 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 56 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 88 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 120 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 16 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 48 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 80 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 112 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 8 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 40 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 72 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 104 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 1 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 32 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 64 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 96 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name milan --time 5 --threads 128 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5