#!/bin/bash
./build/LockTester --name skx --time 5 --threads 1 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "mrw-opt" --distType "static" --ratio 20.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "mrw-opt" --distType "static" --ratio 10.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "mrw-opt" --distType "static" --ratio 5.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "mrw-opt" --distType "static" --ratio 20.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "mrw-opt" --distType "static" --ratio 10.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "mrw-opt" --distType "static" --ratio 5.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "mrw-opt" --distType "static" --ratio 20.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "mrw-opt" --distType "static" --ratio 10.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "mrw-opt" --distType "static" --ratio 5.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "mrw-opt" --distType "static" --ratio 20.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "mrw-opt" --distType "static" --ratio 10.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "mrw-opt" --distType "static" --ratio 5.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "mrw-opt" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "mrw-opt" --distType "static" --ratio 20.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "mrw-opt" --distType "static" --ratio 10.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "mrw-opt" --distType "static" --ratio 5.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "crmr-w" --distType "static" --ratio 20.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "crmr-w" --distType "static" --ratio 10.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "crmr-w" --distType "static" --ratio 5.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "crmr-w" --distType "static" --ratio 20.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "crmr-w" --distType "static" --ratio 10.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "crmr-w" --distType "static" --ratio 5.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "crmr-w" --distType "static" --ratio 20.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "crmr-w" --distType "static" --ratio 10.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "crmr-w" --distType "static" --ratio 5.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "crmr-w" --distType "static" --ratio 20.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "crmr-w" --distType "static" --ratio 10.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "crmr-w" --distType "static" --ratio 5.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "crmr-w" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "crmr-w" --distType "static" --ratio 20.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "crmr-w" --distType "static" --ratio 10.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "crmr-w" --distType "static" --ratio 5.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "cpp-std" --distType "static" --ratio 20.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "cpp-std" --distType "static" --ratio 10.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "cpp-std" --distType "static" --ratio 5.0 --csType "n-mem-1G" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "cpp-std" --distType "static" --ratio 20.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "cpp-std" --distType "static" --ratio 10.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "cpp-std" --distType "static" --ratio 5.0 --csType "n-mem-1G" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "cpp-std" --distType "static" --ratio 20.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "cpp-std" --distType "static" --ratio 10.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "cpp-std" --distType "static" --ratio 5.0 --csType "n-mem-1K" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "cpp-std" --distType "static" --ratio 20.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "cpp-std" --distType "static" --ratio 10.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "cpp-std" --distType "static" --ratio 5.0 --csType "n-mem-1K" --t1 5 --t2 5 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 1 --lockType "cpp-std" --distType "static" --ratio 2.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 8 --lockType "cpp-std" --distType "static" --ratio 20.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 24 --lockType "cpp-std" --distType "static" --ratio 10.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5
./build/LockTester --name skx --time 5 --threads 40 --lockType "cpp-std" --distType "static" --ratio 5.0 --csType "empty" --t1 -1 --t2 -1 --t3 -1 --trials 5