#!/bin/bash
./build/LockTester --name icx --time 5 --threads 1 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 1 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 2 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 2 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 4 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 4 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 6 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 6 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 8 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 8 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 10 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 10 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 12 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 12 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 14 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 14 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 16 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 16 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 18 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 18 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 20 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 20 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 22 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 22 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 24 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 24 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 26 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 26 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 28 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 28 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 30 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 30 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 32 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 32 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 34 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 34 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 36 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 36 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 38 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 38 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 40 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 40 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 42 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 42 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 44 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 44 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 46 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 46 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 48 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 48 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 50 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 50 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 52 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 52 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 54 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 54 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 56 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 56 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 58 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 58 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 60 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 60 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 62 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 62 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 64 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 64 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 66 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 66 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 68 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 68 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 70 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 70 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 72 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 72 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 74 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 74 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 76 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 76 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 78 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 78 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 80 --lockType "mrw-opt" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 80 --lockType "mrw-opt" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 1 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 1 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 2 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 2 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 4 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 4 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 6 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 6 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 8 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 8 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 10 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 10 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 12 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 12 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 14 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 14 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 16 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 16 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 18 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 18 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 20 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 20 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 22 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 22 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 24 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 24 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 26 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 26 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 28 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 28 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 30 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 30 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 32 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 32 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 34 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 34 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 36 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 36 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 38 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 38 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 40 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 40 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 42 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 42 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 44 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 44 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 46 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 46 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 48 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 48 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 50 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 50 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 52 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 52 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 54 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 54 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 56 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 56 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 58 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 58 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 60 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 60 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 62 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 62 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 64 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 64 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 66 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 66 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 68 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 68 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 70 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 70 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 72 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 72 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 74 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 74 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 76 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 76 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 78 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 78 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 80 --lockType "crmr-w" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 80 --lockType "crmr-w" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 1 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 1 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 2 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 2 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 4 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 4 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 6 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 6 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 8 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 8 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 10 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 10 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 12 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 12 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 14 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 14 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 16 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 16 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 18 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 18 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 20 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 20 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 22 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 22 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 24 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 24 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 26 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 26 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 28 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 28 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 30 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 30 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 32 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 32 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 34 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 34 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 36 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 36 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 38 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 38 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 40 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 40 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 42 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 42 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 44 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 44 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 46 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 46 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 48 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 48 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 50 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 50 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 52 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 52 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 54 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 54 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 56 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 56 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 58 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 58 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 60 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 60 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 62 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 62 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 64 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 64 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 66 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 66 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 68 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 68 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 70 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 70 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 72 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 72 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 74 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 74 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 76 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 76 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 78 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 78 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 80 --lockType "cpp-std" --distType "random" --ratio 2.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5
./build/LockTester --name icx --time 5 --threads 80 --lockType "cpp-std" --distType "random" --ratio 10.0 --csType "n-mem-1" --t1 1 --t2 1 --t3 -1 --trials 5